"""HTML comparison report generator."""

from __future__ import annotations

import base64
from pathlib import Path

from scribesim.metrics.suite import MetricResult


def _img_to_base64(path: Path) -> str:
    """Encode an image file as base64 data URI."""
    data = Path(path).read_bytes()
    suffix = Path(path).suffix.lower()
    mime = "image/png" if suffix == ".png" else "image/jpeg"
    b64 = base64.b64encode(data).decode("ascii")
    return f"data:{mime};base64,{b64}"


def generate_report(
    rendered_path: Path,
    target_path: Path,
    results: list[MetricResult],
    composite: float,
    output_path: Path,
) -> Path:
    """Generate an HTML comparison report.

    Embeds images as base64 so the report is self-contained.
    """
    rendered_b64 = _img_to_base64(rendered_path)
    target_b64 = _img_to_base64(target_path)

    def _color(rating: str) -> str:
        return {"good": "#2d7d2d", "okay": "#b8860b", "needs_work": "#cc3333",
                "unavailable": "#999999"}.get(rating, "#666666")

    metric_rows = ""
    for r in results:
        color = _color(r.rating)
        dist = f"{r.distance:.3f}" if r.distance >= 0 else "N/A"
        metric_rows += f"""
        <tr>
            <td>{r.id}</td>
            <td>{r.name}</td>
            <td>{dist}</td>
            <td style="color:{color};font-weight:bold">{r.rating}</td>
            <td class="detail">{r.detail}</td>
        </tr>"""

    html = f"""<!DOCTYPE html>
<html><head><meta charset="utf-8">
<title>ScribeSim Comparison Report</title>
<style>
body {{ font-family: -apple-system, sans-serif; max-width: 1200px; margin: 0 auto; padding: 20px; }}
h1 {{ color: #333; }}
.images {{ display: flex; gap: 20px; margin: 20px 0; }}
.images img {{ max-width: 48%; height: auto; border: 1px solid #ccc; }}
.images .label {{ font-weight: bold; margin-bottom: 5px; }}
table {{ border-collapse: collapse; width: 100%; margin: 20px 0; }}
th, td {{ padding: 8px 12px; text-align: left; border-bottom: 1px solid #ddd; }}
th {{ background: #f5f5f5; }}
.detail {{ font-size: 0.85em; color: #666; }}
.composite {{ font-size: 1.2em; font-weight: bold; margin: 20px 0; }}
</style></head><body>
<h1>ScribeSim Comparison Report</h1>

<div class="images">
<div><div class="label">Rendered</div><img src="{rendered_b64}"></div>
<div><div class="label">Target (manuscript)</div><img src="{target_b64}"></div>
</div>

<table>
<tr><th>ID</th><th>Metric</th><th>Distance</th><th>Rating</th><th>Detail</th></tr>
{metric_rows}
</table>

<div class="composite">Composite Score: {composite:.3f}</div>

<p style="color:#999;font-size:0.8em">Generated by ScribeSim &mdash; TD-003 Parameter Tuning</p>
</body></html>"""

    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(html)
    return output_path
